package chrome

type AXCategory = int

const (
	AX_CATEGORY_DIALOG AXCategory = iota
	AX_CATEGORY_WIDGET
	AX_CATEGORY_DOCUMENT
	AX_CATEGORY_LANDMARK
	AX_CATEGORY_STRUCTURE
	AX_CATEGORY_SECTION
	AX_CATEGORY_SECTIONHEAD
	AX_CATEGORY_GENERIC
)

var AXCategories = map[string][]AXCategory{
	"math":                     {AX_CATEGORY_SECTION},
	"slider":                   {AX_CATEGORY_WIDGET, AX_CATEGORY_STRUCTURE},
	"progressbar":              {AX_CATEGORY_WIDGET, AX_CATEGORY_STRUCTURE},
	"comment":                  {AX_CATEGORY_DOCUMENT},
	"navigation":               {AX_CATEGORY_LANDMARK},
	"sectionhead":              {AX_CATEGORY_SECTIONHEAD},
	"subscript":                {AX_CATEGORY_SECTION},
	"paragraph":                {AX_CATEGORY_SECTION},
	"region":                   {AX_CATEGORY_LANDMARK},
	"listbox":                  {AX_CATEGORY_WIDGET, AX_CATEGORY_SECTION},
	"form":                     {AX_CATEGORY_LANDMARK},
	"window":                   {},
	"caption":                  {AX_CATEGORY_SECTION},
	"mark":                     {AX_CATEGORY_SECTION},
	"tree":                     {AX_CATEGORY_WIDGET, AX_CATEGORY_SECTION},
	"toolbar":                  {AX_CATEGORY_SECTION},
	"application":              {AX_CATEGORY_STRUCTURE},
	"complementary":            {AX_CATEGORY_LANDMARK},
	"suggestion":               {AX_CATEGORY_SECTION},
	"superscript":              {AX_CATEGORY_SECTION},
	"generic":                  {AX_CATEGORY_GENERIC},
	"listitem":                 {AX_CATEGORY_SECTION},
	"deletion":                 {AX_CATEGORY_SECTION},
	"menubar":                  {AX_CATEGORY_WIDGET, AX_CATEGORY_SECTION},
	"tablist":                  {AX_CATEGORY_WIDGET},
	"list":                     {AX_CATEGORY_SECTION},
	"directory":                {AX_CATEGORY_SECTION},
	"composite":                {AX_CATEGORY_WIDGET},
	"treeitem":                 {AX_CATEGORY_WIDGET, AX_CATEGORY_SECTION},
	"columnheader":             {AX_CATEGORY_WIDGET, AX_CATEGORY_SECTION, AX_CATEGORY_SECTIONHEAD},
	"alertdialog":              {AX_CATEGORY_DIALOG, AX_CATEGORY_SECTION},
	"document":                 {AX_CATEGORY_DOCUMENT},
	"separator":                {AX_CATEGORY_WIDGET, AX_CATEGORY_STRUCTURE},
	"status":                   {AX_CATEGORY_SECTION},
	"select":                   {AX_CATEGORY_WIDGET, AX_CATEGORY_SECTION},
	"checkbox":                 {AX_CATEGORY_WIDGET},
	"cell":                     {AX_CATEGORY_SECTION},
	"tabpanel":                 {AX_CATEGORY_SECTION},
	"note":                     {AX_CATEGORY_SECTION},
	"associationlist":          {AX_CATEGORY_SECTION},
	"roletype":                 {},
	"article":                  {AX_CATEGORY_DOCUMENT},
	"heading":                  {AX_CATEGORY_SECTIONHEAD},
	"rowgroup":                 {AX_CATEGORY_STRUCTURE},
	"insertion":                {AX_CATEGORY_SECTION},
	"range":                    {AX_CATEGORY_STRUCTURE},
	"landmark":                 {AX_CATEGORY_LANDMARK},
	"banner":                   {AX_CATEGORY_LANDMARK},
	"input":                    {AX_CATEGORY_WIDGET},
	"textbox":                  {AX_CATEGORY_WIDGET},
	"menuitem":                 {AX_CATEGORY_WIDGET},
	"associationlistitemvalue": {AX_CATEGORY_SECTION},
	"scrollbar":                {AX_CATEGORY_WIDGET, AX_CATEGORY_STRUCTURE},
	"presentation":             {AX_CATEGORY_STRUCTURE},
	"main":                     {AX_CATEGORY_LANDMARK},
	"figure":                   {AX_CATEGORY_SECTION},
	"combobox":                 {AX_CATEGORY_WIDGET},
	"tab":                      {AX_CATEGORY_WIDGET, AX_CATEGORY_SECTIONHEAD},
	"search":                   {AX_CATEGORY_LANDMARK},
	"row":                      {AX_CATEGORY_WIDGET, AX_CATEGORY_SECTION},
	"feed":                     {AX_CATEGORY_SECTION},
	"code":                     {AX_CATEGORY_SECTION},
	"option":                   {AX_CATEGORY_WIDGET},
	"switch":                   {AX_CATEGORY_WIDGET},
	"emphasis":                 {AX_CATEGORY_SECTION},
	"tooltip":                  {AX_CATEGORY_SECTION},
	"structure":                {AX_CATEGORY_STRUCTURE},
	"contentinfo":              {AX_CATEGORY_LANDMARK},
	"strong":                   {AX_CATEGORY_SECTION},
	"term":                     {AX_CATEGORY_SECTION},
	"menuitemcheckbox":         {AX_CATEGORY_WIDGET},
	"menuitemradio":            {AX_CATEGORY_WIDGET},
	"meter":                    {AX_CATEGORY_STRUCTURE},
	"rowheader":                {AX_CATEGORY_WIDGET, AX_CATEGORY_SECTION, AX_CATEGORY_SECTIONHEAD},
	"table":                    {AX_CATEGORY_SECTION},
	"button":                   {AX_CATEGORY_WIDGET},
	"section":                  {AX_CATEGORY_SECTION},
	"treegrid":                 {AX_CATEGORY_WIDGET, AX_CATEGORY_SECTION},
	"group":                    {AX_CATEGORY_SECTION},
	"widget":                   {AX_CATEGORY_WIDGET},
	"searchbox":                {AX_CATEGORY_WIDGET},
	"command":                  {AX_CATEGORY_WIDGET},
	"radio":                    {AX_CATEGORY_WIDGET},
	"link":                     {AX_CATEGORY_WIDGET},
	"dialog":                   {AX_CATEGORY_DIALOG},
	"associationlistitemkey":   {AX_CATEGORY_SECTION},
	"grid":                     {AX_CATEGORY_WIDGET, AX_CATEGORY_SECTION},
	"timer":                    {AX_CATEGORY_SECTION},
	"log":                      {AX_CATEGORY_SECTION},
	"alert":                    {AX_CATEGORY_SECTION},
	"img":                      {AX_CATEGORY_SECTION},
	"radiogroup":               {AX_CATEGORY_WIDGET, AX_CATEGORY_SECTION},
	"menu":                     {AX_CATEGORY_WIDGET, AX_CATEGORY_SECTION},
	"definition":               {AX_CATEGORY_SECTION},
	"blockquote":               {AX_CATEGORY_SECTION},
	"spinbutton":               {AX_CATEGORY_WIDGET, AX_CATEGORY_STRUCTURE},
	"gridcell":                 {AX_CATEGORY_WIDGET, AX_CATEGORY_SECTION},
	"time":                     {AX_CATEGORY_SECTION},
	"marquee":                  {AX_CATEGORY_SECTION},
}
