// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package axextract

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonCc70a961DecodeAxDistillerLibAxextract(in *jlexer.Lexer, out *getNodesResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "nodes":
			if in.IsNull() {
				in.Skip()
				out.Nodes = nil
			} else {
				in.Delim('[')
				if out.Nodes == nil {
					if !in.IsDelim(']') {
						out.Nodes = make([]cdpNode, 0, 0)
					} else {
						out.Nodes = []cdpNode{}
					}
				} else {
					out.Nodes = (out.Nodes)[:0]
				}
				for !in.IsDelim(']') {
					var v1 cdpNode
					(v1).UnmarshalEasyJSON(in)
					out.Nodes = append(out.Nodes, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCc70a961EncodeAxDistillerLibAxextract(out *jwriter.Writer, in getNodesResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"nodes\":"
		out.RawString(prefix[1:])
		if in.Nodes == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Nodes {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v getNodesResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCc70a961EncodeAxDistillerLibAxextract(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v getNodesResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCc70a961EncodeAxDistillerLibAxextract(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *getNodesResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCc70a961DecodeAxDistillerLibAxextract(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *getNodesResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCc70a961DecodeAxDistillerLibAxextract(l, v)
}
func easyjsonCc70a961DecodeAxDistillerLibAxextract1(in *jlexer.Lexer, out *cdpValue) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "type":
			out.Type = string(in.String())
		case "value":
			if m, ok := out.Value.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Value.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Value = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCc70a961EncodeAxDistillerLibAxextract1(out *jwriter.Writer, in cdpValue) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		if m, ok := in.Value.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Value.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Value))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v cdpValue) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCc70a961EncodeAxDistillerLibAxextract1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v cdpValue) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCc70a961EncodeAxDistillerLibAxextract1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *cdpValue) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCc70a961DecodeAxDistillerLibAxextract1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *cdpValue) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCc70a961DecodeAxDistillerLibAxextract1(l, v)
}
func easyjsonCc70a961DecodeAxDistillerLibAxextract2(in *jlexer.Lexer, out *cdpNodeProp) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "value":
			if in.IsNull() {
				in.Skip()
				out.Value = nil
			} else {
				if out.Value == nil {
					out.Value = new(cdpValue)
				}
				(*out.Value).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCc70a961EncodeAxDistillerLibAxextract2(out *jwriter.Writer, in cdpNodeProp) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		if in.Value == nil {
			out.RawString("null")
		} else {
			(*in.Value).MarshalEasyJSON(out)
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v cdpNodeProp) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCc70a961EncodeAxDistillerLibAxextract2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v cdpNodeProp) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCc70a961EncodeAxDistillerLibAxextract2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *cdpNodeProp) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCc70a961DecodeAxDistillerLibAxextract2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *cdpNodeProp) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCc70a961DecodeAxDistillerLibAxextract2(l, v)
}
func easyjsonCc70a961DecodeAxDistillerLibAxextract3(in *jlexer.Lexer, out *cdpNode) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "nodeId":
			out.NodeID = string(in.String())
		case "ignored":
			out.Ignored = bool(in.Bool())
		case "role":
			if in.IsNull() {
				in.Skip()
				out.Role = nil
			} else {
				if out.Role == nil {
					out.Role = new(cdpValue)
				}
				(*out.Role).UnmarshalEasyJSON(in)
			}
		case "name":
			if in.IsNull() {
				in.Skip()
				out.Name = nil
			} else {
				if out.Name == nil {
					out.Name = new(cdpValue)
				}
				(*out.Name).UnmarshalEasyJSON(in)
			}
		case "description":
			if in.IsNull() {
				in.Skip()
				out.Description = nil
			} else {
				if out.Description == nil {
					out.Description = new(cdpValue)
				}
				(*out.Description).UnmarshalEasyJSON(in)
			}
		case "properties":
			if in.IsNull() {
				in.Skip()
				out.Properties = nil
			} else {
				in.Delim('[')
				if out.Properties == nil {
					if !in.IsDelim(']') {
						out.Properties = make([]cdpNodeProp, 0, 2)
					} else {
						out.Properties = []cdpNodeProp{}
					}
				} else {
					out.Properties = (out.Properties)[:0]
				}
				for !in.IsDelim(']') {
					var v4 cdpNodeProp
					(v4).UnmarshalEasyJSON(in)
					out.Properties = append(out.Properties, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "childIds":
			if in.IsNull() {
				in.Skip()
				out.ChildIds = nil
			} else {
				in.Delim('[')
				if out.ChildIds == nil {
					if !in.IsDelim(']') {
						out.ChildIds = make([]string, 0, 4)
					} else {
						out.ChildIds = []string{}
					}
				} else {
					out.ChildIds = (out.ChildIds)[:0]
				}
				for !in.IsDelim(']') {
					var v5 string
					v5 = string(in.String())
					out.ChildIds = append(out.ChildIds, v5)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "backendDOMNodeId":
			out.DomNodeId = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCc70a961EncodeAxDistillerLibAxextract3(out *jwriter.Writer, in cdpNode) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"nodeId\":"
		out.RawString(prefix[1:])
		out.String(string(in.NodeID))
	}
	{
		const prefix string = ",\"ignored\":"
		out.RawString(prefix)
		out.Bool(bool(in.Ignored))
	}
	if in.Role != nil {
		const prefix string = ",\"role\":"
		out.RawString(prefix)
		(*in.Role).MarshalEasyJSON(out)
	}
	if in.Name != nil {
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		(*in.Name).MarshalEasyJSON(out)
	}
	if in.Description != nil {
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		(*in.Description).MarshalEasyJSON(out)
	}
	if len(in.Properties) != 0 {
		const prefix string = ",\"properties\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v6, v7 := range in.Properties {
				if v6 > 0 {
					out.RawByte(',')
				}
				(v7).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if len(in.ChildIds) != 0 {
		const prefix string = ",\"childIds\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v8, v9 := range in.ChildIds {
				if v8 > 0 {
					out.RawByte(',')
				}
				out.String(string(v9))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"backendDOMNodeId\":"
		out.RawString(prefix)
		out.Int64(int64(in.DomNodeId))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v cdpNode) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCc70a961EncodeAxDistillerLibAxextract3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v cdpNode) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCc70a961EncodeAxDistillerLibAxextract3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *cdpNode) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCc70a961DecodeAxDistillerLibAxextract3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *cdpNode) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCc70a961DecodeAxDistillerLibAxextract3(l, v)
}
func easyjsonCc70a961DecodeAxDistillerLibAxextract4(in *jlexer.Lexer, out *AXNodeProp) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Name":
			out.Name = string(in.String())
		case "Value":
			out.Value = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCc70a961EncodeAxDistillerLibAxextract4(out *jwriter.Writer, in AXNodeProp) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"Value\":"
		out.RawString(prefix)
		out.String(string(in.Value))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AXNodeProp) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCc70a961EncodeAxDistillerLibAxextract4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AXNodeProp) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCc70a961EncodeAxDistillerLibAxextract4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AXNodeProp) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCc70a961DecodeAxDistillerLibAxextract4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AXNodeProp) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCc70a961DecodeAxDistillerLibAxextract4(l, v)
}
func easyjsonCc70a961DecodeAxDistillerLibAxextract5(in *jlexer.Lexer, out *AXNode) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Role":
			out.Role = string(in.String())
		case "Name":
			out.Name = string(in.String())
		case "Description":
			out.Description = string(in.String())
		case "Properties":
			if in.IsNull() {
				in.Skip()
				out.Properties = nil
			} else {
				in.Delim('[')
				if out.Properties == nil {
					if !in.IsDelim(']') {
						out.Properties = make([]AXNodeProp, 0, 2)
					} else {
						out.Properties = []AXNodeProp{}
					}
				} else {
					out.Properties = (out.Properties)[:0]
				}
				for !in.IsDelim(']') {
					var v10 AXNodeProp
					(v10).UnmarshalEasyJSON(in)
					out.Properties = append(out.Properties, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "Children":
			if in.IsNull() {
				in.Skip()
				out.Children = nil
			} else {
				in.Delim('[')
				if out.Children == nil {
					if !in.IsDelim(']') {
						out.Children = make([]AXNode, 0, 0)
					} else {
						out.Children = []AXNode{}
					}
				} else {
					out.Children = (out.Children)[:0]
				}
				for !in.IsDelim(']') {
					var v11 AXNode
					(v11).UnmarshalEasyJSON(in)
					out.Children = append(out.Children, v11)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "DomNodeId":
			out.DomNodeId = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCc70a961EncodeAxDistillerLibAxextract5(out *jwriter.Writer, in AXNode) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Role\":"
		out.RawString(prefix[1:])
		out.String(string(in.Role))
	}
	{
		const prefix string = ",\"Name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"Description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"Properties\":"
		out.RawString(prefix)
		if in.Properties == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v12, v13 := range in.Properties {
				if v12 > 0 {
					out.RawByte(',')
				}
				(v13).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"Children\":"
		out.RawString(prefix)
		if in.Children == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v14, v15 := range in.Children {
				if v14 > 0 {
					out.RawByte(',')
				}
				(v15).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"DomNodeId\":"
		out.RawString(prefix)
		out.Int64(int64(in.DomNodeId))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AXNode) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCc70a961EncodeAxDistillerLibAxextract5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AXNode) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCc70a961EncodeAxDistillerLibAxextract5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AXNode) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCc70a961DecodeAxDistillerLibAxextract5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AXNode) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCc70a961DecodeAxDistillerLibAxextract5(l, v)
}
