package aria

var WidgetRoles = map[string]struct{}{
	"alert":            {},
	"alertdialog":      {},
	"button":           {},
	"checkbox":         {},
	"dialog":           {},
	"gridcell":         {},
	"link":             {},
	"log":              {},
	"marquee":          {},
	"menuitem":         {},
	"menuitemcheckbox": {},
	"menuitemradio":    {},
	"option":           {},
	"progressbar":      {},
	"radio":            {},
	"scrollbar":        {},
	"slider":           {},
	"spinbutton":       {},
	"status":           {},
	"tab":              {},
	"tabpanel":         {},
	"textbox":          {},
	"timer":            {},
	"tooltip":          {},
	"treeitem":         {},

	"combobox":   {},
	"grid":       {},
	"listbox":    {},
	"menu":       {},
	"menubar":    {},
	"radiogroup": {},
	"tablist":    {},
	"tree":       {},
	"treegrid":   {},
}

var StructureRoles = map[string]struct{}{
	"article":      {},
	"columnheader": {},
	"definition":   {},
	"directory":    {},
	"document":     {},
	"group":        {},
	"heading":      {},
	"img":          {},
	"list":         {},
	"listitem":     {},
	"math":         {},
	"note":         {},
	"presentation": {},
	"region":       {},
	"row":          {},
	"rowgroup":     {},
	"rowheader":    {},
	"separator":    {},
	"toolbar":      {},
}

var LandmarkRoles = map[string]struct{}{
	"application":   {},
	"banner":        {},
	"complementary": {},
	"contentinfo":   {},
	"form":          {},
	"main":          {},
	"navigation":    {},
	"search":        {},
}
